name: Linux Compilation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka pygame

      - name: Compile with Nuitka
        run: |
          python -m nuitka --standalone --onefile --linux-icon=assets/icon.ico --output-filename=jazz-hero_x86_64 src/main.py
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jazz-hero_linux_x86_64
          path: |
            jazz-hero_x86_64
          include-hidden-files: true