name: Windows Compilation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka pygame

      - name: Compile with Nuitka
        run: |
          echo Yes | nuitka --standalone --onefile --output-filename=jazz-hero_x86_64.exe --windows-icon-from-ico=assets/icon.ico src/main.pyw --windows-console-mode=disable

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jazz-hero_x86_64
          path: jazz-hero_x86_64.exe
          include-hidden-files: true